apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: crossplane-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  project: default
  source:
    chart: crossplane-1.17.0.tgz
    repoURL: https://charts.crossplane.io/stable
    targetRevision: HEAD